name: Deploy Frontend to NAS Server

on:
    push:
        branches:
            - 'main'

env:
    REGISTRY: ghcr.io
    SERVER_NAME: homesage-vue
    SERVER_DOCKER_IMG_NAME: homesage-vue-container
    GITHUB_REPO: Son-Hunseo/HomeSage-Vue

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up SSH connection
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Build and Deploy Docker Image
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.NAS_SERVER_IP }} -p ${{ secrets.NAS_SERVER_PORT }} << 'EOF'
                  cd /volume1/${{ secrets.SSH_USERNAME }}
                  rm -rf ${{ env.SERVER_NAME }}
                  mkdir -p ${{ env.SERVER_NAME }}
                  git clone -b main --single-branch https://github.com/${{ env.GITHUB_REPO }} ${{ env.SERVER_NAME }}
                  cd ${{ env.SERVER_NAME }}

                  # Build Docker image and run
                  docker stop ${{ env.SERVER_DOCKER_IMG_NAME }} || true
                  docker rm ${{ env.SERVER_DOCKER_IMG_NAME }} || true
                  sleep 30
                  docker build \
                    --build-arg VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }} \
                    --build-arg VITE_KAKAO_MAP_KEY=${{ secrets.VITE_KAKAO_MAP_KEY }} \
                    -t ${{ env.SERVER_DOCKER_IMG_NAME }}:latest -f Dockerfile .
                  docker run -d --name ${{ env.SERVER_DOCKER_IMG_NAME }} \
                    -p 5173:80 \
                    ${{ env.SERVER_DOCKER_IMG_NAME }}:latest
                  EOF
